apiVersion: v1
kind: Service
metadata:
  name: grpc-beer-javascript
spec:
  selector:
    app: grpc-beer-javascript
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 9999
      targetPort: http
